services:
  # Servicio PHP-FPM
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: inmotable_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - inmotable_network
    depends_on:
      - mysql

  # Servicio Nginx
  nginx:
    image: nginx:alpine
    container_name: inmotable_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - inmotable_network
    depends_on:
      - app

  # Servicio MySQL
  mysql:
    image: mysql:8.0
    container_name: inmotable_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inmotable_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: inmotable_user
      MYSQL_PASSWORD: inmotable_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inmotable_network

  # Servicio phpMyAdmin (opcional para administrar la BD)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: inmotable_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8081:80"
    networks:
      - inmotable_network
    depends_on:
      - mysql

networks:
  inmotable_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
